### ISSUE TITLE
[Q] Help with PS9829B-based samsung amplifier

### ISSUE THREAD

**Issue by bademux** [zarpli/PS-WTX500#2]
Hi,
Thanks for the project, I read description as a good piece of adventure literature!
And I suddenly realized that [Home Theater HT-THQ25](https://www.samsung.com/uk/support/model/HT-THQ25R/ELS/)  (with integrated amplifier and dvd) whait for its time :)
Looks like Samsung create modular products. Mine consists of 3 boards. Main board, PSU and Amplifier.
The interesting part is amplifier it is based on exactly the same PS9829B chip, but it lacks ADC part ( S4560,  AK5384  and AK5381). Amplifier is connected to motherboard via 32 pin FPC cable (please see image below).
<img src="https://user-images.githubusercontent.com/1610049/102721517-8c1f0600-42fb-11eb-93e8-dc8f00a9425e.png" width="190"/>

| name | FPC | rpi |
| --- | --- | --- |
| TMS (MLRCK) | 11 | LRCK |
| BCK | 12 | BCK |
| TSD0 (MSDIN0) | 13 | DOUT |
|  TSD1 (MSDIN1) | 14 | none |
|  TSD2 (MSDIN2) | 15 | none |
| CS | 17 | SPI_CE0  |
|  MOSI (?) | 18 | SPI_MOSI  |
| SCK | 19  | SPI_SCLK  |
 | MISO (?) |  20  | SPI_MISO  |
 | PS-RST (PDN) (?) | 16 | GPIOX  |
P-ON is located on PSU board. 

Unfortunately my knowledge in electronics is limited, so I want to ask your opinion about my idea:
Is it worth to try attach raspberry pi to amplifier from HT-THQ25 via i2s (PS9818 datasheet states that it is capable to handle i2s) and control it via SPI?
The full idea is to use 5.1 system with 2.1 mode (unfortunately RPI handles only 2 audio channels over i2s) for [Spotify build in client](https://github.com/dtcooper/raspotify) on RPI.

![Bad quality amplified board overview](https://user-images.githubusercontent.com/1610049/102721531-a8bb3e00-42fb-11eb-8573-02e0881c55c7.png)

**Comment by zarpli** [comment]
> Is it worth to try attach raspberry pi to amplifier from HT-THQ25 via i2s (PS9818 datasheet states that it is capable to handle i2s) and control it via SPI?

Yes, it's possible

> The full idea is to use 5.1 system with 2.1 mode (unfortunately RPI handles only 2 audio channels over i2s) for [Spotify build in client](https://github.com/dtcooper/raspotify) on RPI.

I recommend doing unit experiments, you could start with a Teensy Board that has an excellent audio library. You will be able to do multi-channel testing, although you can use one audio channel and repeat it on the outputs you need using the PS9829B settings.

[https://www.pjrc.com/teensy/](url)

please share your project :)

**Comment by bademux** [comment]
Thanks,
Raspberry Pi 1 (or 3) is the only thing I have right now.
Can I please ask you about powering?
I wonder how to power my rpi? Is it possible to power it from standby psu?
Can you please share your connection scheme?
Sure I will share it if project succeed :)

UPD:
Looks like standby line is 5.6V.
Unfortunately latest Teensy 3+ bit pricey, for 4$ there is stm32f4 with 5 i2s.
I found some stm8 boards, will try it with sduino (stm8 arduino).
What is VDD voltage on your board? Is Pro Mini 328 5.6V tolerant? 
To enable PSU connect P-ON to P/S .
Actual research into is here https://gist.github.com/bademux/79821b4e16a3fc60e6667689e656ae2b
